%% Initializing Pi
pi=raspi('169.254.0.2','pi','raspberry');

%% Initialise ros on this PC
setenv('ROS_IP','169.254.0.3');
rosinit

%% SSH the pi
pi.openShell

%% Creating Publishers
capturedImgPub = rospublisher('/tp/capturedImg','sensor_msgs/Image');

FSRPub = rospublisher('/force_sns/newton','std_msgs/Float32');

probePositionPub = rospublisher('/probePosition/x_y','std_msgs/Float32MultiArray');

pwmPubx = rospublisher('/servo_ctrl/s1','std_msgs/Float32');
pwmPuby = rospublisher('/servo_ctrl/s2','std_msgs/Float32');
pwmPubz = rospublisher('/servo_ctrl/s3','std_msgs/Float32');
%% Define Subscribers to the pi topics
rgbSub = rossubscriber('/tp/pi_camera_rgb');
capturedImgSub = rossubscriber('/tp/capturedImg');
FSRsub = rossubscriber('/force_sns/ch0');
FSRsubNewton = rossubscriber('/force_sns/newton');
positionSub = rossubscriber('/probePosition/x_y');

%% Creating UI
figure(1)

camera_axes = axes('position',[0.01 0.68 0.35 0.3]);

edge_axes = axes('position',[0.52 0.68 0.35 0.3]);

% Control Probe z position
touch_up = uicontrol('style', 'pushbutton',...
    'string', 'Probe UP',...
    'units', 'normalized',...
    'position', [0.4 0.25 0.2 0.15], ...
    'callback', {@z_up, pwmPubz});

touch_down = uicontrol('style', 'pushbutton',...
    'string', 'Probe Down',...
    'units', 'normalized',...
    'position', [0.4 0.07 0.2 0.15], ...
    'callback', {@z_down, pwmPubz});

Initial = uicontrol('style', 'pushbutton',...
    'string', 'Initial',...
    'units', 'normalized',...
    'position', [0.7 0.07 0.2 0.15], ...
    'callback', {@initial_pos, probePositionPub, pwmPubz});

Capture = uicontrol('style', 'pushbutton',...
    'string', 'Capture',...
    'units', 'normalized',...
    'position', [0.1 0.47 0.2 0.15], ...
    'callback', {@captureImg, rgbSub.LatestMessage, edge_axes, capturedImgPub});

Blind_Mapping = uicontrol('style', 'pushbutton',...
    'string', 'Blind Mapping',...
    'units', 'normalized',...
    'position', [0.5 0.4 0.2 0.15], ...
    'callback', {@blind_mapping, probePositionPub, pwmPubz, 0.1, FSRsubNewton});

%Slider objects to control probe x-y position
control_y = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '0',...
    'position', [0.01 0.16 0.045 0.27]);

control_x = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '0',...
    'position', [0.1 0.04 0.27 0.05]);

uicontrol('style','text',...
    'units', 'normalized',...
    'string', 'The FSR reading in Newton is',...
    'position', [0.62 0.28 0.27 0.05]);

FSR_readings = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '0',...
    'position', [0.89 0.275 0.1 0.07]);

servo_axes = axes('position',[0.13 0.2 0.24 0.21]);
xlim([0 3])
ylim([0 4])

uicontrol('style','Slider',...
    'Min',0,'Max',4,'Value',0,...
    'units','normalized',...
    'position',[0.06    0.16    0.045    0.27], ...
    'callback',{@write_y_pos, control_x, control_y, servo_axes, probePositionPub});

uicontrol('style','Slider',...
    'Min',0,'Max',3,'Value',0,...
    'units','normalized',...
    'position',[0.1    0.1    0.27    0.05], ....,
    'callback',{@write_pos, control_x, control_y, servo_axes, probePositionPub});

crop_y1 = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '240',...
    'position', [0.42 0.68 0.045 0.15]);

crop_x1 = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '1',...
    'position', [0.52 0.56 0.17 0.05]);

crop_y2 = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '1',...
    'position', [0.42 0.84 0.045 0.15]);

crop_x2 = uicontrol('style','edit',...
    'units', 'normalized',...
    'string', '320',...
    'position', [0.7 0.56 0.17 0.05]);

uicontrol('style','Slider',...
    'Min',120,'Max',240,'Value',120,...
    'units','normalized',...
    'position',[0.47    0.68    0.045    0.15], ...
    'callback',{@editImgYLower, crop_x1, crop_x2, crop_y1, crop_y2, edge_axes, capturedImgPub, capturedImgSub.LatestMessage});

uicontrol('style','Slider',...
    'Min',1,'Max',160,'Value',1,...
    'units','normalized',...
    'position',[0.52    0.62    0.17    0.05], ....,
    'callback',{@editImg, crop_x1, crop_x2, crop_y1, crop_y2, edge_axes, capturedImgPub, capturedImgSub.LatestMessage});

uicontrol('style','Slider',...
    'Min',1,'Max',120,'Value',120,...
    'units','normalized',...
    'position',[0.47    0.84    0.045    0.15], ...
    'callback',{@editImgYUpper, crop_x1, crop_x2, crop_y1, crop_y2, edge_axes, capturedImgPub, capturedImgSub.LatestMessage});

uicontrol('style','Slider',...
    'Min',160,'Max',320,'Value',320,...
    'units','normalized',...
    'position',[0.7    0.62    0.17    0.05], ....,
    'callback',{@editImgXUpper, crop_x1, crop_x2, crop_y1, crop_y2, edge_axes, capturedImgPub, capturedImgSub.LatestMessage});

Start_Mapping = uicontrol('style', 'pushbutton',...
    'string', 'Start Mapping',...
    'units', 'normalized',...
    'position', [0.7 0.4 0.2 0.15], ...
    'callback', {@area_mapping, probePositionPub, pwmPubz, FSRsubNewton, capturedImgSub.LatestMessage, crop_x1, crop_x2, crop_y1, crop_y2});
%% Using Callback Fxns.
FSRsub.NewMessageFcn = @(~,msg)FSR_Newton(FSRPub, msg, FSR_readings);
rgbSub.NewMessageFcn=@(~,msg)camera_show(msg, camera_axes);
positionSub.NewMessageFcn=@(~,msg)adjustProbePosition(pwmPubx, pwmPuby, msg);